name: Sync LeetCode Submissions

on:
  workflow_dispatch: # Allows you to trigger the sync manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run LeetCode Synchronizer
        uses: dos-m0nk3y/LeetCode-Synchronizer@v1.1.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
